package edu.csuft.chentao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import edu.csuft.chentao.pojo.bean.ChattingMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHATTING_MESSAGE".
*/
public class ChattingMessageDao extends AbstractDao<ChattingMessage, Long> {

    public static final String TABLENAME = "CHATTING_MESSAGE";

    /**
     * Properties of entity ChattingMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Userid = new Property(1, int.class, "userid", false, "USERID");
        public final static Property Groupid = new Property(2, int.class, "groupid", false, "GROUPID");
        public final static Property Typemsg = new Property(3, int.class, "typemsg", false, "TYPEMSG");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property Message = new Property(6, String.class, "message", false, "MESSAGE");
        public final static Property Image = new Property(7, byte[].class, "image", false, "IMAGE");
    }


    public ChattingMessageDao(DaoConfig config) {
        super(config);
    }
    
    public ChattingMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHATTING_MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"USERID\" INTEGER NOT NULL ," + // 1: userid
                "\"GROUPID\" INTEGER NOT NULL ," + // 2: groupid
                "\"TYPEMSG\" INTEGER NOT NULL ," + // 3: typemsg
                "\"TYPE\" INTEGER NOT NULL ," + // 4: type
                "\"TIME\" TEXT," + // 5: time
                "\"MESSAGE\" TEXT," + // 6: message
                "\"IMAGE\" BLOB);"); // 7: image
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_CHATTING_MESSAGE_USERID ON CHATTING_MESSAGE" +
                " (\"USERID\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_CHATTING_MESSAGE_GROUPID ON CHATTING_MESSAGE" +
                " (\"GROUPID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHATTING_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChattingMessage entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindLong(2, entity.getUserid());
        stmt.bindLong(3, entity.getGroupid());
        stmt.bindLong(4, entity.getTypemsg());
        stmt.bindLong(5, entity.getType());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(7, message);
        }
 
        byte[] image = entity.getImage();
        if (image != null) {
            stmt.bindBlob(8, image);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChattingMessage entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindLong(2, entity.getUserid());
        stmt.bindLong(3, entity.getGroupid());
        stmt.bindLong(4, entity.getTypemsg());
        stmt.bindLong(5, entity.getType());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(7, message);
        }
 
        byte[] image = entity.getImage();
        if (image != null) {
            stmt.bindBlob(8, image);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChattingMessage readEntity(Cursor cursor, int offset) {
        ChattingMessage entity = new ChattingMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getInt(offset + 1), // userid
            cursor.getInt(offset + 2), // groupid
            cursor.getInt(offset + 3), // typemsg
            cursor.getInt(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // message
            cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7) // image
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChattingMessage entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserid(cursor.getInt(offset + 1));
        entity.setGroupid(cursor.getInt(offset + 2));
        entity.setTypemsg(cursor.getInt(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMessage(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImage(cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChattingMessage entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChattingMessage entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChattingMessage entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
