package edu.csuft.chentao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import edu.csuft.chentao.pojo.bean.GroupChattingItem;
import edu.csuft.chentao.pojo.bean.Groups;

import edu.csuft.chentao.dao.GroupChattingItemDao;
import edu.csuft.chentao.dao.GroupsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupChattingItemDaoConfig;
    private final DaoConfig groupsDaoConfig;

    private final GroupChattingItemDao groupChattingItemDao;
    private final GroupsDao groupsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupChattingItemDaoConfig = daoConfigMap.get(GroupChattingItemDao.class).clone();
        groupChattingItemDaoConfig.initIdentityScope(type);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        groupChattingItemDao = new GroupChattingItemDao(groupChattingItemDaoConfig, this);
        groupsDao = new GroupsDao(groupsDaoConfig, this);

        registerDao(GroupChattingItem.class, groupChattingItemDao);
        registerDao(Groups.class, groupsDao);
    }
    
    public void clear() {
        groupChattingItemDaoConfig.clearIdentityScope();
        groupsDaoConfig.clearIdentityScope();
    }

    public GroupChattingItemDao getGroupChattingItemDao() {
        return groupChattingItemDao;
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

}
