package edu.csuft.chentao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import edu.csuft.chentao.pojo.bean.GroupUser;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_USER".
*/
public class GroupUserDao extends AbstractDao<GroupUser, Long> {

    public static final String TABLENAME = "GROUP_USER";

    /**
     * Properties of entity GroupUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Groupid = new Property(1, int.class, "groupid", false, "GROUPID");
        public final static Property Userid = new Property(2, int.class, "userid", false, "USERID");
    }


    public GroupUserDao(DaoConfig config) {
        super(config);
    }
    
    public GroupUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"GROUPID\" INTEGER NOT NULL ," + // 1: groupid
                "\"USERID\" INTEGER NOT NULL );"); // 2: userid
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_GROUP_USER__id ON GROUP_USER" +
                " (\"_id\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupUser entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindLong(2, entity.getGroupid());
        stmt.bindLong(3, entity.getUserid());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupUser entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindLong(2, entity.getGroupid());
        stmt.bindLong(3, entity.getUserid());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GroupUser readEntity(Cursor cursor, int offset) {
        GroupUser entity = new GroupUser( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getInt(offset + 1), // groupid
            cursor.getInt(offset + 2) // userid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupUser entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGroupid(cursor.getInt(offset + 1));
        entity.setUserid(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GroupUser entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GroupUser entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupUser entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
