package edu.csuft.chentao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import edu.csuft.chentao.pojo.bean.Hint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HINT".
*/
public class HintDao extends AbstractDao<Hint, Long> {

    public static final String TABLENAME = "HINT";

    /**
     * Properties of entity Hint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Image = new Property(1, byte[].class, "image", false, "IMAGE");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Show = new Property(3, int.class, "show", false, "SHOW");
        public final static Property Groupname = new Property(4, String.class, "groupname", false, "GROUPNAME");
        public final static Property Description = new Property(5, String.class, "description", false, "DESCRIPTION");
        public final static Property Groupid = new Property(6, int.class, "groupid", false, "GROUPID");
        public final static Property Userid = new Property(7, int.class, "userid", false, "USERID");
    }


    public HintDao(DaoConfig config) {
        super(config);
    }
    
    public HintDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HINT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"IMAGE\" BLOB," + // 1: image
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"SHOW\" INTEGER NOT NULL ," + // 3: show
                "\"GROUPNAME\" TEXT," + // 4: groupname
                "\"DESCRIPTION\" TEXT," + // 5: description
                "\"GROUPID\" INTEGER NOT NULL ," + // 6: groupid
                "\"USERID\" INTEGER NOT NULL );"); // 7: userid
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_HINT__id ON HINT" +
                " (\"_id\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HINT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Hint entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        byte[] image = entity.getImage();
        if (image != null) {
            stmt.bindBlob(2, image);
        }
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getShow());
 
        String groupname = entity.getGroupname();
        if (groupname != null) {
            stmt.bindString(5, groupname);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(6, description);
        }
        stmt.bindLong(7, entity.getGroupid());
        stmt.bindLong(8, entity.getUserid());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Hint entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        byte[] image = entity.getImage();
        if (image != null) {
            stmt.bindBlob(2, image);
        }
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getShow());
 
        String groupname = entity.getGroupname();
        if (groupname != null) {
            stmt.bindString(5, groupname);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(6, description);
        }
        stmt.bindLong(7, entity.getGroupid());
        stmt.bindLong(8, entity.getUserid());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Hint readEntity(Cursor cursor, int offset) {
        Hint entity = new Hint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getBlob(offset + 1), // image
            cursor.getInt(offset + 2), // type
            cursor.getInt(offset + 3), // show
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // groupname
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // description
            cursor.getInt(offset + 6), // groupid
            cursor.getInt(offset + 7) // userid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Hint entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImage(cursor.isNull(offset + 1) ? null : cursor.getBlob(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setShow(cursor.getInt(offset + 3));
        entity.setGroupname(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDescription(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGroupid(cursor.getInt(offset + 6));
        entity.setUserid(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Hint entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Hint entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Hint entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
